apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-publisher
  annotations:
    iam.gke.io/gcp-service-account: orders-publisher-prod@gke-project-503215.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  annotations:
    iam.gke.io/gcp-service-account: orders-worker-prod@gke-project-503215.iam.gserviceaccount.com
