apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-reader
  namespace: argocd
  annotations:
    iam.gke.io/gcp-service-account: orders-eso@gke-project-503215.iam.gserviceaccount.com
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: argocd
spec:
  provider:
    gcpsm:
      projectID: gke-project-503215
      auth:
        workloadIdentity:
          clusterLocation: europe-west2
          clusterName: dev
          clusterProjectID: gke-project-503215
          serviceAccountRef:
            name: secret-reader
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: repo-harbor-orders
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: repo-harbor-orders
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: git@github.com:Mustafa12z/harbor-orders.git
        sshPrivateKey: "{{ .sshKey }}"
  data:
    - secretKey: sshKey
      remoteRef:
        key: orders-argocd-repo-ssh-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-google-oauth
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        dex.google.clientID: "{{ .clientID }}"
        dex.google.clientSecret: "{{ .clientSecret }}"
  data:
    - secretKey: clientID
      remoteRef:
        key: orders-argocd-google-oauth
        property: clientID
    - secretKey: clientSecret
      remoteRef:
        key: orders-argocd-google-oauth
        property: clientSecret
