apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    gcpsm:
      projectID: gke-project-503215
      auth:
        workloadIdentity:
          # Cluster project / location / name — patched per env when needed.
          clusterLocation: europe-west2
          clusterName: dev
          clusterProjectID: gke-project-503215
          serviceAccountRef:
            name: secret-reader
