apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - smoke-postsync.yaml
  - deployment-marker.yaml
  - migrate-presync.yaml
configMapGenerator:
  - name: db-migrations
    files:
      - 0001_baseline.sql
      - 0002_align_notification_shipping.sql
    options:
      disableNameSuffixHash: true
      annotations:
        argocd.argoproj.io/sync-wave: "0"
