apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orders
resources:
  - env-value.yaml
  - ../../base
  - ingress.yaml
  - managed-certificate.yaml
  - ../../base/observability
  - ../../base/externalsecrets
  - ../../base/hooks
  - ../../rollouts

patches:
  - path: hpa-patch.yaml
  - path: sa-annotations.yaml
  - path: eso-patch.yaml
  - path: config-patch.yaml

# Pin by digest once app-ci has built images. Until then, :bootstrap is pushed
# by infra-ci (after Terraform, before Argo). See docs/versioning.md.
images:
  - name: europe-west2-docker.pkg.dev/gke-project-503215/gke-orders/api-gateway
    digest: sha256:379d9978827e67778b3550decb5f9ebc3a4153966d49c55c769a8aa4ab668db6
  - name: europe-west2-docker.pkg.dev/gke-project-503215/gke-orders/order-service
    digest: sha256:986e255f97ab8cc531a5f1d8a0be9a99ce5c9066974f72b7f9761861e1a64500
  - name: europe-west2-docker.pkg.dev/gke-project-503215/gke-orders/inventory-service
    digest: sha256:e86261d6d8bdb4aabef268a715eca9f0f857165cc970fc73cd33a3d4890491aa
  - name: europe-west2-docker.pkg.dev/gke-project-503215/gke-orders/payment-service
    digest: sha256:129b005ceb414f63cf91395d7cdd3e9fe24c80c6d5ea82a3d75fc57e67f7aee4
  - name: europe-west2-docker.pkg.dev/gke-project-503215/gke-orders/notification-service
    digest: sha256:063311930a054c62b0456c6a6d0fd84dea70725d34390c586eb3a8b12ab4056b
  - name: europe-west2-docker.pkg.dev/gke-project-503215/gke-orders/shipping-service
    digest: sha256:0cf56499ac1b66f156510d27feebc939b5506743134675ece37966245ab9aaea
  - name: europe-west2-docker.pkg.dev/gke-project-503215/gke-orders/worker
    digest: sha256:15f37930a8b70cd749d6575fa3b58a7ca86c711b26ffa14253080d141961cf04
  - name: europe-west2-docker.pkg.dev/gke-project-503215/gke-orders/scheduler
    digest: sha256:d26aeb1151bb3dae0a2cc1f813f34292de516f761dfec768b10d17e946501025
  - name: europe-west2-docker.pkg.dev/gke-project-503215/gke-orders/dashboard-api
    digest: sha256:09f66e58ad3534f795c05fe24835ce575298bc39b74023531d2f4e36f5ad6127

replacements:
  - source:
      kind: ConfigMap
      name: rollout-env
      fieldPath: data.environment
    targets:
      - select:
          kind: Rollout
        fieldPaths:
          - spec.strategy.canary.steps.*.analysis.args.[name=environment].value
        options:
          create: false
