apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-publisher
  annotations:
    iam.gke.io/gcp-service-account: orders-publisher-staging@gke-project-503215.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  annotations:
    iam.gke.io/gcp-service-account: orders-worker-staging@gke-project-503215.iam.gserviceaccount.com
